BitirmeTezi/Models/ErrorViewModel.cs
namespace BitirmeTezi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BitirmeTezi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAcceLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace BitirmeTezi.Controllers
{
    public class AboutController : Controller
    {
        OurTeamManager Otm = new OurTeamManager(new EOurTeamRepository());
        public IActionResult Index()
        {
            var val = Otm.GetListWithStatus();
            return View(val);
        }
    }
}

BitirmeTezi/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using DataAcceLayer.EntityFramework;
using Entitylayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace BitirmeTezi.Controllers
{
    public class ContactController : Controller
    {
        
        ContactManager Cm = new ContactManager(new EContactRepository());

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (!ModelState.IsValid) { 
           
            }
            else {
                contact.ContactStatus = true;
                Cm.ContactAdd(contact);
            }
            return View();
        }
    }
}

BitirmeTezi/Controllers/ErrorPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace BitirmeTezi.Controllers
{
    public class ErrorPageController : Controller
    {
        public IActionResult Error1(int code)
        {
            return View();
        }
    }
}

BitirmeTezi/Controllers/HomeController.cs
using BitirmeTezi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using BusinessLayer.Concrete;
using DataAcceLayer.EntityFramework;
using X.PagedList.Mvc;
using X.PagedList.Mvc.Core;
using Entitylayer;
using X.PagedList;

namespace BitirmeTezi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        WorkManager Wm = new WorkManager(new EWorkRepository());
        OurServiceManager Osm = new OurServiceManager(new EOurServiceRepository());
        
        public IActionResult Index()
        {
            var Val = Wm.GetListWithCategoryStatus();
            
            Val.Reverse();
            
            return View(Val);
        }
        

        
        
        public IActionResult OurServiceDetail(int id)
        {
            var val = Osm.GetById(id);
            return View(val);
        }

      
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BitirmeTezi/Controllers/WorkController.cs
using BusinessLayer.Concrete;
using DataAcceLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;


namespace BitirmeTezi.Controllers
{
    public class WorkController : Controller
    {
        WorkManager Wm = new WorkManager(new EWorkRepository());
        public IActionResult Index()
        {
            var Val = Wm.GetListWithCategoryStatus();




            return View(Val);
        }
        public IActionResult WorkDetail(int id)
        {
            var val = Wm.GetByID(id);
            return View(val);
        }
    }
}

BitirmeTezi/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BitirmeTezi.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BitirmeTezi/Pages/_Host.cshtml
@page "/login"
@namespace BitirmeTezi.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

<component type="typeof(App)" render-mode="ServerPrerendered" />

BitirmeTezi/Pages/_Layout.cshtml
@using Microsoft.AspNetCore.Components.Web
@namespace BitirmeTezi.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en"
      class="light-style layout-menu-fixed  "
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="/Admin/assets/"
      data-template="vertical-menu-template-free">


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link rel="icon" type="image/x-icon" href="/img/IWEX.ico" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="/css/errorstyle.css" />
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="/Admin/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="/Admin/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="/Admin/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="/Admin/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="/Admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="/Admin/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="/Admin/assets/js/config.js"></script>
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap.min.css.map" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/BitirmeTezi.styles.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" />
    <link href="~/css/bootstrap/bootstrap.min.css" />
    <link href="_content/Syncfusion.Blazor.Themes/bootstrap5.css" rel="stylesheet" />
    <script src="_content/Syncfusion.Blazor.Core/scripts/syncfusion-blazor.min.js"
            type="text/javascript"></script>
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="/Admin/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="/Admin/assets/vendor/libs/popper/popper.js"></script>
    <script src="/Admin/assets/vendor/js/bootstrap.js"></script>
    <script src="/Admin/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="/Admin/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="/Admin/assets/js/main.js"></script>

    <!-- Page JS -->
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="_framework/blazor.server.js"></script>
</body>
</html>

BitirmeTezi/Views/About/Index.cshtml
@model List<Entitylayer.Concrete.OurTeam>
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- Start Banner Hero -->
<section class="bg-light w-100">
    <div class="container">
        <div class="row d-flex align-items-center py-5">
            <div class="col-lg-6 text-start">
                <h1 class="h2 py-5 text-primary typo-space-line">Hakkımızda</h1>
                <p class="light-300">
                    IWEX olarak bir yazılım şirketi olup, web sitesi, mobil uygulama, logo tasarımı ve reklamcılık gibi birçok alanda müşterilerimize hizmet veriyoruz. Bu çok yönlü hizmetlerimiz sayesinde, farklı sektörlerden siz değerli müşterilerimize hitap ederek ihtiyaçlarınıza en uygun çözümler sunuyoruz. Bu özelliklerimiz, müşterilerimizin işlerini kolaylaştırıp, onların başarısına katkıda bulunacaktır.
                </p>
            </div>
            <div class="col-lg-6">
                <img src="./img/banner-img-02.svg">
            </div>
        </div>
    </div>
</section>
<!-- End Banner Hero -->
<!-- Start Team Member -->
<section class="container py-5">
    <div class="pt-5 pb-3 d-lg-flex align-items-center gx-5">

        <div class="col-lg-3" style="top:0">
            <h2 class="h2 py-5 typo-space-line">Ekibimiz</h2>
            <p class="text-muted light-300">
               Ekibimiz Sizlerin Hizmetinde
            </p>
        </div>

        <div class="col-lg-9 row">
            @foreach (var item in Model)
            {
                <div class="team-member col-md-4">
                    <img class="team-member-img img-fluid rounded-circle p-4" src="~/img/@item.OurTeamImage" alt="Card image" style="object-fit:cover;aspect-ratio:4/4">
                    <ul class="team-member-caption list-unstyled text-center pt-4 text-muted light-300">
                        <li>@item.OurTeamName</li>
                        <li>@item.OurTeamJob</li>
                    </ul>
                </div>
            }



        </div>

    </div>
</section>
<!-- End Team Member -->
<!-- Start Our Partner -->
<section class="bg-secondary py-3">
    <div class="container py-5">
        <h2 class="h2 text-white text-center py-5">İş Ortaklarımız</h2>
        <div class="row text-center">
            <div class="col-md-3 mb-3">
                <div class="card partner-wap py-5">
                    <a href="#"><img style="width:100px" src="~/img/duzceuni.png" /></a>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card partner-wap py-5">
                    <a href="#"><i class='display-1 bx text-white bxs-check-shield bx-lg'></i></a>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card partner-wap py-5">
                    <a href="#"><i class='display-1 text-white bx bxs-bolt-circle'></i></a>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="card partner-wap py-5">
                    <a href="#"><i class='display-1 text-white bx bxs-spa'></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Our Partner-->
<!-- Start Progress -->

<!-- End Progress -->
<!-- Start Choice -->
<div class="container my-4">
    <div class="row">
        <div class="banner-img col-lg-5">
            <img src="./assets/img/work.svg" class="rounded img-fluid" alt="">
        </div>
        <div class="banner-content col-lg-7 align-self-end">
            <h2 class="h2 pb-3">Neden Bizi Seçmelisiniz ?</h2>
            <p class="text-muted pb-5 light-300">
                  Özgün web siteleri tasarlıyoruz, Yazmaktan sıkılmıyoruz.
                    Güncel çizgiler kullanarak, kaliteli ve özgün içerikler hazırlıyoruz. Sizi ve firmanızı en doğru şekilde tanıtıyor, sizi müşterilerinize en iyi şekilde yansıtacak web tasarımları hazırlıyoruz. 
                    Profesyonel, hızlı, arama motoru dostu web siteleri tasarlıyoruz. Taleplerinizi doğru anlıyor, sorunlarınıza hızlı çözümler üretiyoruz.
                    Aldığımız işi tüm kontroller yapıldıktan sonra hatasız olarak zamanında teslim ediyoruz.
        </div>
    </div>
</div>

<!-- End Choice -->
<!-- Start Aim -->
<section class="banner-bg bg-white py-5">
    <div class="container my-4">
        <div class="row text-center">

            <div class="objective col-lg-4">
                <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                    <i class="display-4 bx bxs-bulb text-light"></i>
                </div>
                <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Vizyonumuz</h2>
                <p class="light-300">
                    Güvenilir bir iş yol izleyerek projelerimizi sizlere sunmak.
                </p>
            </div>

            <div class="objective col-lg-4 mt-sm-0 mt-4">
                <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                    <i class='display-4 bx bx-revision text-light'></i>
                </div>
                <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Görevimiz</h2>
                <p class="light-300">
                   Sizlerin isteklerini dikkate alarak, size en verimli şekilde hizmet vermek.
                </p>
            </div>

            <div class="objective col-lg-4 mt-sm-0 mt-4">
                <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                    <i class="display-4 bx bxs-select-multiple text-light"></i>
                </div>
                <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Hedefimiz</h2>
                <p class="light-300">
                    Bölgenin en başarılı yazılım şirketi olmak.
                </p>
            </div>

        </div>
    </div>
</section>
<!-- End Aim -->

BitirmeTezi/Views/ErrorPage/Error1.cshtml
@{Layout=null;}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Tempalte by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="~/css/errorstyle.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
			</div>
			<h2>404 - Page not found</h2>
			<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
			<a  asp-controller="Home" asp-action="Index">Go To Homepage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

BitirmeTezi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    int sayac = 0;
}
@model List<Entitylayer.Work>


<!-- Start Banner Hero -->
<div class="banner-wrapper bg">
    <div  id="index_banner" class="banner-vertical-center-index container-fluid pt-5">

        <!-- Start slider -->
        @await Component.InvokeAsync("AnnouncementList")
        <!-- End slider -->

    </div>
</div>
<!-- End Banner Hero -->
<!-- Start Service -->
<section class="service-wrapper py-3">
    <div class="container-fluid pb-3">
        <div class="row">
            <h2 class="h2 text-center col-12 py-5 semi-bold-600">Neden Bizi Tercih Etmelisiniz</h2>
            <div class="service-header col-2 col-lg-3 text-end light-300">
                <i class='bx bx-gift h3 mt-1'></i>
            </div>
            <div class="service-heading col-10 col-lg-9 text-start float-end light-300">
                <h2 class="h3 pb-4 typo-space-line">Gelecek İçin Başarı</h2>

            </div>
        </div>
        <p class="service-footer col-10 offset-2 col-lg-9 offset-lg-3 text-start pb-3 text-muted px-2">
           Müşteri memnuniyetini önemsiyor ve her zaman bu mottoda çalışıyoruz.
        </p>

    </div>

    <div class="service-tag py-5 bg-secondary">
        <div class="col-md-12">
            <h3 class="h3 text-center col-12 semi-bold-600" style="color:white;">SON İŞLERİMİZ</h3>
        </div>
    </div>

</section>

<section class="container overflow-hidden py-5">
    <div class="row gx-5 gx-sm-3 gx-lg-5 gy-lg-5 gy-3 pb-3 projects">
        @foreach (var item in Model)
        {
            
                if (sayac < 8)
            {
                <!-- Start Recent Work -->
                <div class="col-xl-3 col-md-4 col-sm-6 project @item.category.CategoryName">
                    <a asp-action="WorkDetail" asp-route-id="@item.WorkID" asp-controller="Work" class="service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0">
                        <img class="service card-img" src="./img/@item.WorkImage" alt="Card image" style="object-fit:cover;aspect-ratio:4/3">
                        <div class="service-work-vertical card-img-overlay d-flex align-items-end">
                            <div class="service-work-content text-left text-light">
                             
                                <h3>@item.WorkTitle</h3>
                                <p class="card-text">
                                    @{

                                        if (item.WorkContent != null)
                                        {
                                            if (item.WorkContent.Length > 50)
                                            {
                                            <p> @item.WorkContent.Substring(0, 50)...</p>
                                            }
                                            else
                                            {
                                            <p>@item.WorkContent</p>
                                            }
                                        }

                                    }
                                </p>
                                <span class="btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300">@item.category.CategoryName</span>
                            </div>
                        </div>
                    </a>
                </div>

                <!-- End Recent Work -->
            }
                else
            {
                break;
            }

            sayac++; 
            
           

        }
    </div>
</section>
<!-- End Service -->
<!-- Start View Work -->
<section class="bg-secondary">
    <div class="container py-5">
        <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-2 col-12 text-light align-items-center">
                <i class='display-1 bx bxs-box bx-lg'></i>
            </div>
            <div class="col-lg-7 col-12 text-light pt-2">
                <h3 class="h4 light-300">Başarıyı Yakalamak İçin</h3>
                <p class="light-300">Bizi Tercih Edin.</p>
            </div>
            <div class="col-lg-3 col-12 pt-4">
                <a asp-action="Work" asp-controller="Home" class="btn btn-primary rounded-pill btn-block shadow px-4 py-2">İşlerimize Gözat</a>
            </div>
        </div>
    </div>
</section>
<!-- End View Work -->
<!-- Start Recent Work -->
<section class="py-5 mb-5">
    <div class="container">
        <div class="recent-work-header row text-center pb-5">
            <h2 class="col-md-6 m-auto h2 semi-bold-600 py-5">Çalışma Alanlarımız</h2>
        </div>
        <div class="row gy-5 g-lg-5 mb-4">

            @await Component.InvokeAsync("OurServiceList")
        </div>
    </div>
</section>
<!-- End Recent Work -->

BitirmeTezi/Views/Home/OurServiceDetail.cshtml
@model Entitylayer.Concrete.OurService

<section class="container py-5">



    <div class="row d-flex pb-5">
        <div class="col-lg-5 offset-lg-0 col-md-8 offset-md-2">
            <img class="rounded float-right " style="object-fit:cover; aspect-ratio:4/3;width:100%" src="~/img/@Model.OurServiceimg">
        </div>

        <div class="col-lg-7">

            <!-- Start Pricing List -->
            <h1 class="top-0 text-center">@Model.OurServiceName</h1>
            <p>@Model.OurServiceDesc</p>



        </div>
    </div>
</section>

BitirmeTezi/Views/Shared/Components/CategoryList/Default.cshtml
@model List<Entitylayer.Category>

<div class="service-tag py-5 bg-secondary">
    <div class="col-md-12">
        <ul class="nav d-flex justify-content-center">
            <li class="nav-item mx-lg-4">
                <a class="filter-btn nav-link btn-outline-primary active shadow rounded-pill text-light px-4 light-300" href="#" data-filter=".project">All</a>
            </li>
            @foreach (var item in Model)
            {
                
                     <li class="nav-item mx-lg-4">
                    <a class="filter-btn nav-link btn-outline-primary rounded-pill text-light px-4 light-300" href="#" data-filter=".@item.CategoryName">@item.CategoryName</a>
                    </li>
                

               
            }

        </ul>
    </div>
</div>

BitirmeTezi/Views/Work/Index.cshtml
@using Entitylayer.Concrete

@model List<Entitylayer.Work>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Start Our Work -->
@await Component.InvokeAsync("CategoryList")
<section class="container py-5">


    <div class="row projects gx-lg-5">
        @foreach (var item in Model)
        {
            <a asp-route-id="@item.WorkID" asp-controller="Work" asp-action="WorkDetail" class="col-sm-6 col-lg-4 text-decoration-none project @item.category.CategoryName">
                <div class="service-work overflow-hidden card mb-5 mx-5 m-sm-0">
                    <img class="card-img-top" src="~/img/@item.WorkImage" alt="..." style="object-fit:cover;aspect-ratio:4/3">
                    <div class="card-body">
                        <h5 class="card-title light-300 text-dark">@item.WorkTitle</h5>
                        <p class="card-text light-300 text-dark">
                            @if (item.WorkContent.Length > 75)
                            {
                                @item.WorkContent.Substring(0,75)
                            }
                            else
                            {
                                @item.WorkContent
                            }

                        </p>
                        <span class="text-decoration-none text-primary light-300">
                            Devamını Gör <i class='bx bxs-hand-right ms-1'></i>
                        </span>
                    </div>
                </div>
            </a>
        }



    </div>
    <br />
    <br />
    <br />






</section>
<!-- End Our Work -->
<!-- Start Banner Hero -->
<div id="work_banner" class="banner-wrapper bg-light w-100 py-5">
    <div class="banner-vertical-center-work container text-light d-flex justify-content-center align-items-center py-5 p-0">
        <div class="banner-content col-lg-8 col-12 m-lg-auto text-center">
            <h1 class="banner-heading h2 display-3 pb-5 semi-bold-600 typo-space-line-center">Projelerimiz</h1>
            <h3 class="h4 pb-2 regular-400">Yazılım Projelerimizin Özellikleri</h3>
            <p class="banner-body pb-2 light-300">

                Yazılım projelerimiz, işletmenizin ihtiyaçlarına özel çözümler sunarak, kaliteli kodlama ile yazılmış ve uzun vadeli destek sağlanan yazılımlar olacaktır.
                Ayrıca işletmenizin ihtiyaçlarına ve stratejik hedeflerine uygun olarak geliştirilen yazılım çözümlerimiz ile işletmenizin verimliliğini artırıp,
                zorluklarla başa çıkmanıza yardımcı olacak ve inovatif çözümler üreterek işletmenizin rekabet gücünü artırmayı hedefliyoruz.
            </p>

            <a href="/Contact">  <button type="submit" class="btn rounded-pill btn-secondary text-light px-4 light-300">Bize Ulaşın</button></a>
            <a href="/About">    <button type="submit" class="btn rounded-pill btn-outline-light px-4 me-4 light-300">Daha Fazlası</button></a>

        </div>
    </div>
</div>
<!-- End Banner Hero -->
<!-- Start Feature Work -->
<section class="bg-light py-5">
    <div class="feature-work container my-4">
        <div class="row d-flex d-flex align-items-center">
            <div class="col-lg-5">
                <h3 class="feature-work-title h4 text-muted light-300"></h3>
                <h1 class="feature-work-heading h2 py-3 semi-bold-600">Projelerimizde Sizlere Neler Sunuyoruz</h1>
                <p class="feature-work-body text-muted light-300">


                </p>
                <p class="feature-work-footer text-muted light-300">
                    <li>Özel yazılım çözümleri: İşletmenizin ihtiyaçlarına uygun özel yazılım çözümleri geliştiriyoruz. </li>
                    <li>Web uygulamaları: Özel web uygulamaları geliştiriyoruz ve mevcut uygulamalarınızın performansını iyileştiriyoruz.</li>
                    <li>Mobil uygulamalar: Özel mobil uygulamalar geliştiriyoruz ve mevcut uygulamalarınızın performansını iyileştiriyoruz.</li>
                    <li>Veri analizi: İşletmenizin verilerini analiz ediyor, anlamlı sonuçlar çıkartıyor ve bu sonuçlar doğrultusunda önerilerde bulunuyoruz.</li>
                    <li>Bulut hizmetleri: İşletmeniz için özel bulut hizmetleri çözümleri geliştiriyoruz ve mevcut hizmetlerinizi iyileştiriyoruz.</li>
                    <li>Destek ve bakım: Geliştirdiğimiz yazılımların düzgün çalışmasını sağlıyor ve mevcut yazılımlarınızın performansını iyileştirmeye yardımcı oluyoruz.</li>
                </p>
            </div>
            <div class="col-lg-6 offset-lg-1 align-left">
                <div class="row">
                    <a class="col" data-type="image">
                        <img class="img-fluid" src="~/img/aciklama1.png">
                    </a>
                    <a class="col" data-type="image">
                        <img class="img-fluid" src="~/img/aciklama2.png">
                    </a>
                </div>
                <div class="row pt-4">
                    <a class="col" data-type="image">
                        <img class="img-fluid" src="~/img/aciklama3.png">
                    </a>
                    <a class="col" data-type="image">
                        <img class="img-fluid" src="~/img/aciklama4.png">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Feature Work -->

BitirmeTezi/Views/Work/WorkDetail.cshtml
@model Entitylayer.Work

<section class="container py-5">



    <div class="row d-flex pb-5">
        <div class="col-lg-5 offset-lg-0 col-md-8 offset-md-2">
            <img class="rounded float-right " style="object-fit:cover; aspect-ratio:4/3;width:100%" src="~/img/@Model.WorkImage">
        </div>

        <div class="col-lg-7">

            <!-- Start Pricing List -->
            <h1 class="top-0 text-center">@Model.WorkTitle</h1>
            <p>@Model.WorkContent</p>



        </div>
    </div>
</section>